# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Bump iOS version"
  private_lane :bump_version do |options|
    build = options[:build]
    branch = git_branch()

    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["APP"]
    )

    build_number = build || latest_release[:buildVersion].to_i + 1
    
    increment_build_number({ build_number: build_number })

    commit_message = "Bump example iOS version to: " + build_number

    commit_version_bump(
      message: commit_message + " [skip ci]"
    )

    puts "Bumped example app iOS version to: " + build_number

    if branch == "main"
      puts "On `main`, creating PR ..."

      create_pull_request(
        repo: "gr4vy/gr4vy-react-native",
        title: commit_message,
        labels: "internal",
        base: "main",
        reviewers: "luca-gr4vy"
      )

      puts "Done! Please review and approve the created PR at" + lane_context[SharedValues::CREATE_PULL_REQUEST_HTML_URL]
    else
      puts "Pushing changes to branch `" + branch + "` ..."
    end
  end

  desc "Build and distribute beta"
  lane :beta do |options|
    bump_version(build: options[:build] || nil)

    build_app(
      scheme: "EmbedReactNativeExample",
      export_method: "ad-hoc",
      export_options: {
      provisioningProfiles: { 
        ENV["BUNDLE_ID"] => ENV["PROVISIONING_PROFILE_NAME"],
      }
    }
    )

    firebase_app_distribution(
      app: ENV["APP"],
      groups: ENV["GROUPS"],
      release_notes: options[:notes] || ""
    )
  end
end
