name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    # - name: Enable Corepack before setting up Node
    #   shell: bash
    #   run: |
    #     npm install -g yarn@1.22.15
    #     yarn --version
    #     npm install -g corepack@0.24.0
    #     corepack --version
    #     corepack enable

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        SKIP_YARN_COREPACK_CHECK=1 yarn install --cwd example --frozen-lockfile
        yarn install --frozen-lockfile
      shell: bash
