# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Bump Android version"
  private_lane :bump_version do |options|
    build = options[:build]
    branch = git_branch()

    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["APP"]
    )

    build_number = build || latest_release[:buildVersion].to_i + 1
    
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
      version_code: build_number
    )

    commit_message = "Bump example Android version to: " + build_number.to_s

    commit_android_version_bump(
      message: commit_message + " [skip ci]"
    )

    puts "Bumped example app Android version to: " + build_number.to_s

    puts "token: " + ENV["GITHUB_TOKEN"]

    if branch == "task/beta-releases"
      puts "On `main`, creating PR ..."

      create_pull_request(
        api_token: ENV["GITHUB_TOKEN"],
        repo: "gr4vy/gr4vy-react-native",
        title: commit_message,
        labels: "internal",
        head: "chore/bump-example-version",
        base: "main",
        reviewers: "luca-gr4vy"
      )

      puts "Done! Please review and approve the created PR at" + lane_context[SharedValues::CREATE_PULL_REQUEST_HTML_URL].to_s
    else
      puts "Pushing changes to branch `" + branch + "` ..."

      push_to_git_remote

      puts "Done!"
    end
  end

  desc "Build and distribute beta"
  lane :beta do |options|
    bump_version(build: options[:build] || nil)

    gradle(
      task: "clean assembleRelease"
    )

    firebase_app_distribution(
      app: ENV["APP"],
      groups: ENV["GROUPS"],
      release_notes: options[:notes] || ""
    )
  end
end
